### PR TITLE
Add remote for Porthole

### PR DESCRIPTION
**Pull request by boyvanamstel**
Remote control for the OS X app [Porthole](http://www.getporthole.com). It allows you to toggle individual AirPlay speakers, connect to all, disconnect from all and change the volume.

Let me know where to send a screenshot.

Not sure if this is known: adding a <list> to the interface seems to prevent remotes from working in the browser on a desktop computer.

### CODE REVIEW

**Comment by ui-philip** [comment]
You can attach a screenshot as a comment here for the time being. "adding a to the interface"? Not sure what you mean. Thanks!

**Comment by boyvanamstel** [comment]
Markdown crippled my comment. I meant to say: "adding a list element to the interface", as I've done to list the AirPlay speakers.

Screenshot: unifiedremote-porthole

**Comment by boyvanamstel** [comment]
Hey guys, could you add this remote to the release version of Unified Remote? I'm anxious to start marketing this on Porthole's main page as a new feature. Thanks!

Boy

**Comment by ui-philip** [comment]
Yup, it'll be included in the next release of UR. ETA next week!

**Pull request merged**
